{"name": "test_001", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './temp/temp_pic.png'", "trace": "self = <TestCase.test_engine.TestAdmin object at 0x10220e9c0>\ndrivers = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"023ce7c708a2f9ac773d76b5215afcc1\")>\n\n    @allure.story('租户登录用例')\n    def test_001(self,drivers):\n        login = Login(drivers)\n        with allure.step('打开DSMP'):\n            login.get_url(ini.url)\n            login.click_pass_button()\n        with allure.step('租户登录'):\n            login.click_ns_login_button()\n            login.input_nsname(ini.ns)\n            login.click_next_button()\n            login.input_username(ini.username)\n            login.input_password(ini.password)\n            login.input_verify_code(ini.verify_code)\n            login.click_login_button()\n        with allure.step('判断是否登录成功'):\n            text=login.get_url_now()\n            log.info(text)\n            assert 'dashboard' in text\n>           save_pic(drivers)\n\ntest_engine.py:42: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../utils/picture_save.py:7: in save_pic\n    allure.attach.file(\"./temp/temp_pic.png\", attachment_type=allure.attachment_type.PNG)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/allure_commons/_allure.py:203: in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_hooks.py:513: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/allure_pytest/listener.py:256: in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/allure_commons/reporter.py:160: in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_hooks.py:513: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/allure_commons/logger.py:39: in report_attached_file\n    shutil.copy2(source, destination)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/shutil.py:475: in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nsrc = './temp/temp_pic.png'\ndst = PosixPath('/Users/a1234/dsmp-selenium+pytest+allure/TestCase/report/result/8d7be9de-142f-4b7f-8e47-6307526f8802-attachment.png')\n\n    def copyfile(src, dst, *, follow_symlinks=True):\n        \"\"\"Copy data from src to dst in the most efficient way possible.\n    \n        If follow_symlinks is not set and src is a symbolic link, a new\n        symlink will be created instead of copying the file it points to.\n    \n        \"\"\"\n        sys.audit(\"shutil.copyfile\", src, dst)\n    \n        if _samefile(src, dst):\n            raise SameFileError(\"{!r} and {!r} are the same file\".format(src, dst))\n    \n        file_size = 0\n        for i, fn in enumerate([src, dst]):\n            try:\n                st = _stat(fn)\n            except OSError:\n                # File most likely does not exist\n                pass\n            else:\n                # XXX What about other special files? (sockets, devices...)\n                if stat.S_ISFIFO(st.st_mode):\n                    fn = fn.path if isinstance(fn, os.DirEntry) else fn\n                    raise SpecialFileError(\"`%s` is a named pipe\" % fn)\n                if _WINDOWS and i == 0:\n                    file_size = st.st_size\n    \n        if not follow_symlinks and _islink(src):\n            os.symlink(os.readlink(src), dst)\n        else:\n>           with open(src, 'rb') as fsrc:\nE           FileNotFoundError: [Errno 2] No such file or directory: './temp/temp_pic.png'\n\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/shutil.py:260: FileNotFoundError"}, "steps": [{"name": "打开DSMP", "status": "passed", "start": 1722925311345, "stop": 1722925314020}, {"name": "租户登录", "status": "passed", "start": 1722925314020, "stop": 1722925319584}, {"name": "判断是否登录成功", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './temp/temp_pic.png'\n", "trace": "  File \"/Users/a1234/dsmp-selenium+pytest+allure/TestCase/test_engine.py\", line 42, in test_001\n    save_pic(drivers)\n  File \"/Users/a1234/dsmp-selenium+pytest+allure/utils/picture_save.py\", line 7, in save_pic\n    allure.attach.file(\"./temp/temp_pic.png\", attachment_type=allure.attachment_type.PNG)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/allure_commons/_allure.py\", line 203, in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    raise exception.with_traceback(exception.__traceback__)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/allure_pytest/listener.py\", line 256, in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/allure_commons/reporter.py\", line 160, in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    raise exception.with_traceback(exception.__traceback__)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/allure_commons/logger.py\", line 39, in report_attached_file\n    shutil.copy2(source, destination)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/shutil.py\", line 475, in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/shutil.py\", line 260, in copyfile\n    with open(src, 'rb') as fsrc:\n         ^^^^^^^^^^^^^^^\n"}, "attachments": [{"source": "8d7be9de-142f-4b7f-8e47-6307526f8802-attachment.png", "type": "image/png"}], "start": 1722925319584, "stop": 1722925320121}], "attachments": [{"name": "log", "source": "f30a44ed-62d8-4a32-9301-116c9c09a458-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "34f611a9-9f6b-4e98-8bde-207914814e3a-attachment.txt", "type": "text/plain"}], "start": 1722925311344, "stop": 1722925320124, "uuid": "47d1ff0e-31f8-4f1f-8530-ec71f7efaf97", "historyId": "b78e1ee49d35c1fbfe85a85029f54549", "testCaseId": "b78e1ee49d35c1fbfe85a85029f54549", "fullName": "TestCase.test_engine.TestAdmin#test_001", "labels": [{"name": "story", "value": "租户登录用例"}, {"name": "feature", "value": "测试引擎管理功能"}, {"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_engine"}, {"name": "subSuite", "value": "TestAdmin"}, {"name": "host", "value": "1234s-MacBook-Air.local"}, {"name": "thread", "value": "94539-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_engine"}]}